package frc.autogenerated;

/**
 * Automatically generated file containing build version information.
 */
public final class BuildConstants {
    public static final String MAVEN_GROUP = "";
    public static final String MAVEN_NAME = "Off-Season-2024";
    public static final String VERSION = "unspecified";
    public static final int GIT_REVISION = 97;
    public static final String GIT_SHA = "289aa21f5b2774217b45e3246141b1b1e2409e26";
    public static final String GIT_DATE = "2024-04-10 15:47:44 GMT";
    public static final String GIT_BRANCH = "pre-pre-commit";
    public static final String BUILD_DATE = "2024-04-10 15:49:37 GMT";
    public static final long BUILD_UNIX_TIME = 1712764177217L;
    public static final int DIRTY = 0;

    private BuildConstants() {}
}
