package frc.autogenerated;

/**
 * Automatically generated file containing build version information.
 */
public final class BuildConstants {
    public static final String MAVEN_GROUP = "";
    public static final String MAVEN_NAME = "Off-Season-2024";
    public static final String VERSION = "unspecified";
    public static final int GIT_REVISION = 103;
    public static final String GIT_SHA = "d9b7001353d20e39d5c477ed4b401f348483db07";
    public static final String GIT_DATE = "2024-04-10 15:52:30 GMT";
    public static final String GIT_BRANCH = "pre-pre-commit";
    public static final String BUILD_DATE = "2024-04-10 15:53:22 GMT";
    public static final long BUILD_UNIX_TIME = 1712764402165L;
    public static final int DIRTY = 1;

    private BuildConstants() {}
}
