package frc.robot.statemachine.superstructure;

public enum SuperstructureState {

	STAY_IN_PLACE,
	IDLE,
	IDLE_AFTER_ALGAE_REMOVE,
	INTAKE,
	OUTTAKE,
	ARM_PRE_SCORE,
	PRE_SCORE,
	SCORE_WITHOUT_RELEASE,
	SCORE,
	CLOSE_L4,
	POST_ALGAE_REMOVE,
	ALGAE_REMOVE,
	ALGAE_OUTTAKE,
	PRE_NET,
	NET_WITHOUT_RELEASE,
	NET_WITH_RELEASE,
	PROCESSOR_OUTTAKE,
	PRE_CLIMB,
	CLIMB,
	STOP_CLIMB,
	CLOSE_CLIMB;

}
