package frc.robot.statemachine.superstructure;

public enum SuperstructureState {

	IDLE,
	INTAKE,
	OUTTAKE,
	ARM_PRE_SCORE,
	PRE_SCORE,
	SCORE_WITHOUT_RELEASE,
	SCORE,
	ALGAE_REMOVE_WITHOUT_INTAKE,
	ALGAE_REMOVE_WITH_INTAKE,
	ARM_PRE_ALGAE_REMOVE,
	PRE_ALGAE_REMOVE,
	ALGAE_OUTTAKE;

}
