package frc.robot.subsystems.algaeIntake;

public enum AlgaeIntakeState {

	CLOSED,
	INTAKE,
	TRANSFER_TO_END_EFFECTOR_WITHOUT_RELEASE,
	TRANSFER_TO_END_EFFECTOR_WITH_RELEASE,
	OUTTAKE_WITHOUT_RELEASE,
	OUTTAKE_WITH_RELEASE,
	HOLD_ALGAE,
	STAY_IN_PLACE

}
