#!/bin/bash

GREEN='\033[0;32m'
RED='\033[0;31m'
NO_COLOR='\033[0m'

echo "*********************************************************"
echo "Running git post-checkout hook. Running Git Pull... "
echo "---------------------------------------------------------"

# Run git pull and capture the output and exit status
output=$(git pull 2>&1)
status=$?

# Check the status and print the output in the corresponding color
if [ $status -eq 0 ]; then
    echo -e "${GREEN}$output${NO_COLOR}"
else
    echo -e "${RED}$output${NO_COLOR}"
fi

echo "*********************************************************"

branch_name=$(git rev-parse --abbrev-ref HEAD) # Save current branch name
[[ "$branch_name" == *-test ]] || exit 0 # Check if test branch
dev_branch="${branch_name%-test}" # Save dev branch name

# Check if the dev branch exists
git show-ref --verify --quiet "refs/heads/$dev_branch" || {
  echo "Branch $dev_branch does not exist"
  exit 0
}

echo "Checking if up to date with dev branch..."
echo "---------------------------------------------------------"

# Check if branches are up-to-date
if git merge-base --is-ancestor "$dev_branch" "$branch_name"; then
  echo -e "${GREEN}Already up-to-date with branch $dev_branch${NO_COLOR}"
else
  echo -e "${RED}$branch_name is not up-to-date with branch $dev_branch${NO_COLOR}"
fi

echo "*********************************************************"
