#!/bin/bash
echo "*********************************************************"
echo "Running git post-checkout hook. Running Git Pull... "
echo "*********************************************************"

# run git pull
git pull;
