#!/bin/bash
echo "*********************************************************"
echo "Running git post-commit hook. Running Git Push... "
echo "*********************************************************"

branch=$(git branch --show-current)

# run git pull
git push -u origin "$branch";
