package frc.robot.statemachine;

public enum RobotState {

	STAY_IN_PLACE,
	DRIVE,
	INTAKE,
	CORAL_OUTTAKE,
	ELEVATOR_OPENING,
	ARM_PRE_SCORE,
	PRE_SCORE,
	SCORE_WITHOUT_RELEASE,
	SCORE,
	ALGAE_REMOVE,
	ALGAE_OUTTAKE_FROM_END_EFFECTOR,
	ALGAE_OUTTAKE_FROM_INTAKE,
	ALGAE_INTAKE,
	TRANSFER_ALGAE_TO_END_EFFECTOR,
	HOLD_ALGAE,
	PRE_NET,
	NET,
	PROCESSOR_SCORE,
	PROCESSOR_NO_SCORE,
	PRE_CLIMB,
	CLIMB_WITHOUT_LIMIT_SWITCH,
	CLIMB_WITH_LIMIT_SWITCH,
	MANUAL_CLIMB,
	EXIT_CLIMB,
	STOP_CLIMB,
	CLOSE_CLIMB;

}
