package frc.robot.statemachine;

public enum RobotState {

	STAY_IN_PLACE,
	DRIVE,
	INTAKE,
	CORAL_OUTTAKE,
	ALIGN_REEF,
	ARM_PRE_SCORE,
	PRE_SCORE,
	SCORE_WITHOUT_RELEASE,
	SCORE,
	ALGAE_REMOVE,
	ALGAE_OUTTAKE,
	PRE_NET,
	NET_WITHOUT_RELEASE,
	NET_WITH_RELEASE,
	PROCESSOR_SCORE,
	PRE_CLIMB_WITH_AIM_ASSIST,
	PRE_CLIMB_WITHOUT_AIM_ASSIST,
	CLIMB,
	STOP_CLIMB,
	CLOSE_CLIMB;

}
