name: Auto-update PRs from main

on:
  push:
    branches:
      - master

jobs:
  update-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth setup-git
          gh auth status

      - name: Auto-merge main into PRs with 'autoupdate' label
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DEFAULT_BRANCH="master"
          
          echo "Fetching PRs labeled 'autoupdate'..."
          PRS=$(gh pr list --state open --json number,headRefName,labels --jq \
            '.[] | select(.labels | any(.name == "autoupdate")) | "\(.number) \(.headRefName)"')

          if [ -z "$PRS" ]; then
            echo "No PRs found with label 'autoupdate'."
            exit 0
          fi

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          echo "$PRS" | while read pr_number branch; do
            echo "Updating PR #$pr_number (branch: $branch)..."

            git fetch origin "$DEFAULT_BRANCH"
            git fetch origin "$branch"

            git checkout "$branch"
            git merge origin/"$DEFAULT_BRANCH" --no-edit || {
              echo "Merge conflict in PR #$pr_number (branch: $branch). Skipping."
              continue
            }

            git push origin "$branch"
            echo "Successfully updated PR #$pr_number (branch: $branch)"
          done
