name: Auto-update PR branches

on:
  push:
    branches:
      - master  # or your default branch

permissions:
  contents: write
  pull-requests: write

jobs:
  update-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Authenticate GitHub CLI
        run: gh auth setup-git
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-update PRs with label 'autoupdate'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Looking for PRs labeled 'autoupdate'..."

          PRS=$(gh pr list --state open --json number,labels,isCrossRepository,mergeable,headRefName --jq \
            '.[] | select(.labels | any(.name == "autoupdate")) | select(.isCrossRepository | not) | select(.mergeable == "MERGEABLE") | .number')

          if [ -z "$PRS" ]; then
            echo "No eligible PRs found."
            exit 0
          fi

          for pr in $PRS; do
            echo "Updating PR #$pr..."

            # Checkout the PR branch
            gh pr checkout "$pr"

            # Fetch the latest `master` branch
            git fetch origin master

            # Merge `master` into the PR branch
            git merge origin/master --no-edit

            # Push the changes to the PR branch
            git push origin HEAD

            echo "Successfully updated PR #$pr with the latest `master` changes."
          done
